### ISSUE TITLE
Znane težave / To-do

### ISSUE THREAD

**Issue by enej-ls** [enej-ls/recsa#1]
# Znane težave / To-do
- [ ] V bibliografiji je razmik med vrsticami in med različnimi viri premajhen (moral bi biti 1,5 z dodanim prostorom po odstavku). Glede tega se mi a priori poraja dvom, ali je to sploh možno diktirati na citacijski strani, ali je striktno v domeni urejevalnika besedila.
- [ ] Avtomatsko številčenje spletnih virov. Podobno kot zgoraj nisem še gotov, če je to možno avtomatizirati s citacijsko kodo.
- [ ] Pri virih, ki zahtevajo tudi URL, manjka niz "URL: " pred samo povezavo. Manjša, hitro rešljiva napaka.
- [ ] Naslovi publikacij, ki se končajo z ločilom (npr. "Pannonia or Lower Illyricum?") dobijo v bibliografiji za ločilom v naslovu še piko. Kot zgoraj sumim, da citacijska koda zaradi pomanjkanja pogojnih stavkov o tem ne more nič.
## Že popravljeno
- [x] Citati v tekstu z več avtorji uporabijo (tako kot je sicer v bibliografiji prav), besedico "in" pred zadnjim avtorjem, morale bi biti le vejice.
- [x] Če je specificiran prevajalec publikacije, se v bibliografiji navede podobno kot urednik. Prevajalec ne bi nikoli smel biti naveden v bibliografiji.
- [x] V bibliografiji je pred imenom zbirke vejica namesto vezaja.
- [x] Uredniki z več imeni se zdaj v bibliografiji izpišejo pravilno s presledkom med začetnicami imen, ki je prej manjkal (npr. novo: "Frere, S. S.", staro: "Frere, S.S.")
- [x] Ko ima urednik publikacije več imen, med začetnicami manjkajo presledki. Trenutno se torej izpiše "V: Turfa, J.M. (ur.)" namesto "V: Turfa, J. M. (ur.)". Manjša, hitro rešljiva napaka.
